services:

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: ecommerce_backend
    depends_on:
      - redis
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
